<?php

namespace Esprit\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * AnnonceRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class AnnonceRepository extends EntityRepository
{
    public function getAllAnnonces($currentPage = 1)
    {
        // Create our query
        $query = $this->createQueryBuilder('p')

            ->getQuery();

        // No need to manually get get the result ($query->getResult())

        $paginator = $this->paginate($query, $currentPage);

        return $paginator;
    }

    public function getUserAnnonces($currentPage = 1,$id){



        $query = $this->createQueryBuilder('p')

            ->where('p.idUser = :iduser')
            ->setParameter('iduser', $id)  // we pass directly the shop id
            ->getQuery();



        $paginator = $this->paginate($query, $currentPage);

        return $paginator;


    }

    public function getAllVeh(){

        $query = $this->createQueryBuilder('p')

            ->getQuery();

        $query->getResult();
    }


    /**
     * Paginator Helper
     *
     * Pass through a query object, current page & limit
     * the offset is calculated from the page and limit
     * returns an `Paginator` instance, which you can call the following on:
     *
     *     $paginator->getIterator()->count() # Total fetched (ie: `5` posts)
     *     $paginator->count() # Count of ALL posts (ie: `20` posts)
     *     $paginator->getIterator() # ArrayIterator
     *
     * @param Doctrine\ORM\Query $dql   DQL Query Object
     * @param integer            $page  Current page (defaults to 1)
     * @param integer            $limit The total number per page (defaults to 5)
     *
     * @return \Doctrine\ORM\Tools\Pagination\Paginator
     */
    public function paginate($dql, $page = 1, $limit = 5)
    {
        $paginator = new Paginator($dql);

        $paginator->getQuery()
            ->setFirstResult($limit * ($page - 1)) // Offset
            ->setMaxResults($limit); // Limit

        return $paginator;
    }
}
